baseURL = ""
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "almeida-cv"
title = "resume daan wassink"

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
colorPrimary = "#e93d34"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#f5f5f5"
colorSecondary = "#aaa"
pages = 1
